### ISSUE TITLE
Can share a bit more about the post-processing?

### ISSUE THREAD

**Issue by BarCodeReader** [AlbertSuarez/object-cut#6]
Thanks for your great work!

can share some ideas about the post-processing module?
or does it also included in this repo?

Really appreciate if you can reply.

Have a nice day.

**Comment by adriacabeza** [comment]
Hi, glad you like it!

The idea behind the post-processing module was to improve the predictions of BASNet after doing empirical testing with several images. We saw that some images had undesirable borders, especially with difficult images like trees of hair and a slight lack of sharpness in the results. So we did the following: 

- Perform a small erosion to the predicted mask. This allows us to remove the small undesired borders. We prefer to get rid of those even if it means that we delete very thin parts of the mask. 
- Applying a sharpening algorithm (unsharp masking): the main idea behind the algorithm is to create a blurry image (i.e. using a Gaussian filter) and subtracting it from the original one to detect the presence of the edges (the unsharp mask), like a high-pass filter. Then the mask is applied to the original one resulting in a sharpened image. 

After that, we can use the mask to "cut" the object from the image.

> The post-processing module is included in the repo as well 😄
